<?php

namespace Designbycode\Sluggable\Tests;

use Designbycode\Sluggable\SluggableServiceProvider;
use Illuminate\Support\Facades\Schema;
use Orchestra\Testbench\TestCase as Orchestra;

class TestCase extends Orchestra
{
    public function setUp(): void
    {
        parent::setUp();

        Schema::create('posts', function ($table) {
            $table->id();
            $table->string('title');
            $table->string('slug')->unique();
            $table->timestamps();
        });
    }

    protected function tearDown(): void
    {
        Schema::drop('posts');

        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    protected function getPackageProviders($app)
    {
        return [
            SluggableServiceProvider::class,
        ];
    }

    public function getEnvironmentSetUp($app)
    {
        $app['config']->set('database.default', 'sqlite');
        $app['config']->set('database.connections.sqlite', [
            'driver' => 'sqlite',
            'database' => ':memory:',
            'prefix' => '',
        ]);
    }
}
