<?php

namespace Designbycode\Sluggable;

use Illuminate\Support\ServiceProvider;

class SluggableServiceProvider extends ServiceProvider
{
    public function boot()
    {
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
